Repository The-Standard-Organization/STX.EFxceptions.Cosmos, pull requests merged in 2024-01, with the labels that each got.

#16 DOCUMENTATION: Readme Init
  README.md
  Resources/Diagrams/drawio.txt
  Resources/Images/EFxceptions-Cosmos.png
  Resources/Images/EFxceptions-Cosmos_128.png
  Resources/Images/EFxceptions-Cosmos_256.png
  Resources/Images/EFxceptions-Cosmos_48.png
  Resources/Images/EFxceptions-Cosmos_512.png
  Resources/Images/stx.efCosmos_git_logo.png
  Resources/Images/stx.efxCosmos.icns
  Resources/Images/stx.efxCosmos.ico
Labels: DOCUMENTATION

#8 EXPOSERS: Initialize EFxceptionsContext
  STX.EFxceptions.Cosmos.Base/Services/Foundations/CosmosEFxceptionService .cs
  STX.EFxceptions.Cosmos.Tests.Unit/STX.EFxceptions.Cosmos.Tests.Unit.csproj
  STX.EFxceptions.Cosmos/EFxceptionsContext.cs
  STX.EFxceptions.Cosmos/STX.EFxceptions.Cosmos.csproj
Labels: EXPOSERS

#13 EXPOSERS: Initialize EFxceptionsIdentityContext
  STX.EFxceptions.Identity.Cosmos/EFxceptionsIdentityContext.cs
  STX.EFxceptions.Identity.Cosmos/STX.EFxceptions.Identity.Cosmos.csproj
Labels: EXPOSERS

#15 CODE RUB: General Code Cleanups
  STX.EFxceptions.Cosmos.Tests.Unit/STX.EFxceptions.Cosmos.Tests.Acceptance.csproj
  STX.EFxceptions.Cosmos.sln
  STX.EFxceptions.Identity.Cosmos.Tests.Unit/STX.EFxceptions.Identity.Cosmos.Tests.Acceptance.csproj
Labels: CODE RUB

#18 CODE RUB: Change Type of Exception
  STX.EFxceptions.Cosmos.Base.Tests.Unit/Services/Foundations/CosmosEfxceptionServiceTests.Exceptions.cs
  STX.EFxceptions.Cosmos.Base/STX.EFxceptions.Cosmos.Base.csproj
  STX.EFxceptions.Cosmos.Base/Services/Foundations/CosmosEFxceptionService .cs
  STX.EFxceptions.Cosmos.Base/Services/Foundations/CosmosEFxceptionService.Validations.cs
  STX.EFxceptions.Cosmos.Base/Services/Foundations/ICosmosEFxceptionService.cs
  STX.EFxceptions.Cosmos/EFxceptionsContext.cs
  STX.EFxceptions.Cosmos/STX.EFxceptions.Cosmos.csproj
  STX.EFxceptions.Identity.Cosmos/EFxceptionsIdentityContext.cs
  STX.EFxceptions.Identity.Cosmos/STX.EFxceptions.Identity.Cosmos.csproj
Labels: CODE RUB

#21 ACCEPTANCE: EFxceptionsContext
  STX.EFxceptions.Cosmos.Tests.Acceptance/EFxceptionsContextTests.Logic.cs
  STX.EFxceptions.Cosmos.Tests.Acceptance/EFxceptionsContextTests.cs
  STX.EFxceptions.Cosmos.Tests.Acceptance/Models/Client.cs
  STX.EFxceptions.Cosmos.Tests.Acceptance/MyEFxceptionsContext.cs
  STX.EFxceptions.Cosmos.Tests.Acceptance/STX.EFxceptions.Cosmos.Tests.Acceptance.csproj
  STX.EFxceptions.Cosmos.sln
  STX.EFxceptions.Cosmos/STX.EFxceptions.Cosmos.csproj
  STX.EFxceptions.Identity.Cosmos.Tests.Acceptance/STX.EFxceptions.Identity.Cosmos.Tests.Acceptance.csproj
Labels: ACCEPTANCE

#25 CONFIG: Upgrade Packages
  STX.EFxceptions.Cosmos.Base.Tests.Unit/STX.EFxceptions.Cosmos.Base.Tests.Unit.csproj
  STX.EFxceptions.Cosmos.Base/STX.EFxceptions.Cosmos.Base.csproj
  STX.EFxceptions.Identity.Cosmos/STX.EFxceptions.Identity.Cosmos.csproj
Labels: CONFIG
